AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "**/*.gemspec"

Naming/FileName:
  Exclude:
    - "lib/rubocop-rspec_parity.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
